// export const baseURL = 'https://codegem.glitch.me'
export const baseURL = "http://localhost:5000";
export const adminEmail = 'naumanch969@gmail.com'


export const programmingLanguages = [
    "HTML",
    "CSS",
    "JavaScript",
    "Java",
    "Python",
    "R",
    "C",
    "C++",
    "C#",
    "PHP",
    "TypeScript",
    "Swift",
    "Kotlin",
    "Ruby",
    "Go",
    "SQL",
    "Perl",
    "Scala",
    "Rust",
    "Objective-C",
    "Shell",
    "Lua",
    "Assembly",
    "Dart",
    "MATLAB",
    "Groovy",
    "Visual Basic",
    "Delphi",
    "Haskell",
    "Julia",
    "PowerShell",
    "Clojure",
    "Elixir",
    "F#",
    "Scheme",
    "Fortran",
    "COBOL",
    "Ada",
    "Lisp",
    "Prolog",
    "Smalltalk",
    "Racket",
    "Erlang",
    "Verilog",
    "VHDL",
    "Ada",
    "Scratch",
    "Bash",
    "Tcl",
    "Forth"
];
